/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.esoco.lib.expression.monad;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
